services:
  jobs.database:
    image: postgres:17.2-alpine3.21
    container_name: jobs.database
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: dotnet-job-bank_db
    ports:
      - "5433:5432"
    volumes:
      - db-postgres-data:/var/lib/postgresql/data

volumes:
  db-postgres-data: